### ISSUE TITLE
[EPIC] Move build/release automation to GH Actions

### ISSUE THREAD

**Issue by galal-hussein** [rancher/ecm-distro-tools#375]
This epic issue is to track the effort of moving the automation of build and release of the following repositories to Github action instead of Drone:

- [ ] Use GH actions for build/release - image-build-base
- [ ] Use GH actions for build/release - image-build-kubernetes
- [ ] Use GH actions for build/release - image-build-rke2-cloud-provider
- [ ] Use GH actions for build/release - image-build-flannel
- [ ] Use GH actions for build/release - image-build-calico
- [ ] Use GH actions for build/release - image-build-coredns
- [ ] Use GH actions for build/release - image-build-multus
- [ ] Use GH actions for build/release - image-build-whereabouts

The migration should involve migrating the PR drone and push drone as well, which will include:
- indicating successful/failure builds
- in case of release:
  - release any related artifacts to the github release
  - the push of the related docker images to docker hub

**Comment by manuelbuil** [comment]
There are a few more projects:
* https://github.com/rancher/image-build-k8s-metrics-server
* https://github.com/rancher/image-build-cluster-proportional-autoscaler
* https://github.com/rancher/image-build-dns-nodecache
* all sriov related projects
* https://github.com/rancher/image-build-containerd ?
* https://github.com/rancher/image-build-runc ?

**Comment by briandowns** [comment]
https://github.com/rancher/ecm-distro-tools/blob/master/docs/rke2-dependencies.md

**Comment by manuelbuil** [comment]
https://github.com/rancherlabs/eio/issues/2106

**Comment by galal-hussein** [comment]
I will add the rest of the images to the list, so that we can create related issues for them, also we would need to document the process here so that we have consistency between the repos

**Comment by cwayne18** [comment]
Are we also doing the switch to either `scratch` or `bci-busybox` at teh same time?

**Comment by galal-hussein** [comment]
> Are we also doing the switch to either `scratch` or `bci-busybox` at the same time?

I don't think we should, I think these series of PRs can act as a template for any other project that we need to move to GH action, so I think its better if we separete the moving to bci-busybox to another series of PRs

**Comment by caroline-suse-rancher** [comment]
The idea right now, is that this effort will be complete by June sometime, though I know we're blocked on an EIO step right now. I will update here as I know more. Thank you all!

**Comment by galal-hussein** [comment]
### This is a small guide that should be applied for any new image/repo that we want to migrate to GH Actions:

### Image repos (image-build-*)
---

#### Step 1 - Remove Drone Traces

All traces of drone must be removed, that includes:
- `.drone.yml` file
- `TAG ?= ${DRONE_TAG}` in the makefile
- updatecli - remove drone if mentioned from updatecli

#### Step 2 - Remove manifest

Since we are using buildx now to support multiarch builds, then there is no need for manifest.tmpl, this should be removed from:
- Makefile: 
```
.PHONY: image-manifest
image-manifest:
	DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create --amend \
		$(ORG)/hardened-<image>:$(TAG) \
		$(ORG)/hardened-<image>:$(TAG)-$(ARCH)
	DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push \
		$(ORG)/hardened-<image>:$(TAG)
```

- manifest.tmpl file

#### Step 3 - Add log to the makefile
The idea of the migration is simple, basically includes adding a log section to the makefile which will print all important environment variables that are given by tags or PRs and will be used by the github actions:
Makefile
```
.PHONY: log
log:
	@echo "ARCH=$(ARCH)"
	@echo "TAG=$(TAG)"
	@echo "ORG=$(ORG)"
	@echo "PKG=$(PKG)"
	@echo "SRC=$(SRC)"
	@echo "BUILD_META=$(BUILD_META)"
	@echo "K3S_ROOT_VERSION=$(K3S_ROOT_VERSION)"
	@echo "UNAME_M=$(UNAME_M)"
```

And then it can be used in the github action as follows:
```
run: |
        echo "$(make -s log | grep TAG)" >> "$GITHUB_ENV"
```

#### Step 4 - Add `.github/workflow` files

For image repos we should have 2 main files:

1- `.github/workflows/build.yml` (see [flannel repo](https://github.com/rancher/image-build-flannel/blob/master/.github/workflows/build.yml) as a reference)
2- `.github/workflows/image-push.yml` (see [flannel repo](https://github.com/rancher/image-build-flannel/blob/master/.github/workflows/image-push.yml) as a reference)

The `build.yml` file simply builds the images for amd64, arm64 architectures and then runs trivy for scans, and image-push does the same thing but with push set to true.

Note that you would need to set the proper permissions on the pipeline for the image-push workflow

**Comment by thomasferrandiz** [comment]
@galal-hussein very good summary, that's exactly what we did in the PRs already merged

**Comment by manuelbuil** [comment]
great summary! Maybe warn users that the way to fetch dockerhub secrets changed. Now we use a EIO github action and read the username and password from an env variable
