### ISSUE TITLE
[charts-build-scripts] technical debt of charts-build-scripts

### ISSUE THREAD

**Issue by nicholasSUSE** [rancher/ecm-distro-tools#438]
### Scope
The [charts-build-scripts repo](https://github.com/rancher/charts-build-scripts) is now owned by the release team. 

It is an ancient and legacy code with few portions of new code.

This repository handles 2 specific responsibilities across several features:
- Charts generation and development work 
- Charts release process 

The `release-team` has higher standards of go code quality therefor the `charts-build-scripts` must be improved.

### Tasks
- [ ] Remove the pkg directory
- [ ] Scope lock all err values
- [ ] Use 0 value declaration
- [ ] Unexport all exposed symbols that don't need to be
- [ ] Condense the packages down to what is necessarily needed for APIs
- [ ] Update file names to conform with standards
