### ISSUE TITLE
[charts] Release v2.9.1 and v2.8.7 prime only

### ISSUE THREAD

**Issue by nicholasSUSE** [rancher/ecm-distro-tools#465]
Track all Helm Charts Release process activities for: [charts repository](https://github.com/rancher/charts)

--- 

#### Task Checklist
- [x] Coordination charts release between teams. 
- [x] Execute batch releases
- [x] Clean up old branch 2.8
- [x] Update branch references on Rancher before release.
- [x] Update branch references on Rancher after release. 
- [x] Update product confluence table with necessary chart versions. 
--- 

#### Task Info 

`Coordination charts release between teams`:
- Negotiate with @Jono-SUSE-Rancher the due date for the Charts release.
- Create confluence Page for Charts coordination 2.9.1 and 2.8.7.
- Communicate with company at #team-rancher-release-coordination channel the proper dates and tables.

`Execute batch releases for 2.9.1 and 2.8.7`:
- Merge the batch releases.
- Sync and clean-up dev branches after batch release.
- Forward-port released charts from previous branches.
- Release forward-ported charts from previous branches.
- Sync and clean-up one last time.
- Monitor git mirror
- Communicate result to the company. 

`Update branch references for 2.9.1 and 2.8.7 on Rancher before release`:
- Merge update from `dev-v2.*` to `release-v2.*` branch references.

`Update branch references for 2.9.1 and 2.8.7 on Rancher after release`:
- Merge update from `release-v2.*` back to `dev-v2.*` branch references

**Comment by nicholasSUSE** [comment]
Release PRs for 2.9.1:
- https://github.com/rancher/charts/pull/4338
- https://github.com/rancher/charts/pull/4364
- https://github.com/rancher/charts/pull/4357

Forward-port PRs:
- https://github.com/rancher/charts/pull/4371

Release PRs for 2.8.7:
- https://github.com/rancher/charts/pull/4369
- https://github.com/rancher/charts/pull/4347

**Comment by nicholasSUSE** [comment]
Clean up PRs:
- https://github.com/rancher/charts/pull/4373
- https://github.com/rancher/charts/pull/4372
