### ISSUE TITLE
[charts] Release v2.9.3, v2.8.9, v2.7.16

### ISSUE THREAD

**Issue by tashima42** [rancher/ecm-distro-tools#485]
Track all Helm Charts Release process activities for: [charts repository](https://github.com/rancher/charts)

Rancher 2.7.16 - Prime Only
Rancher 2.8.9 - Prime Only
Rancher 2.9.3 - Prime & Community Maintenance

--- 

#### Task Checklist
- [x] Coordination charts release between teams. 
- [x] Execute batch releases
- [x] Forward Port released charts from 2.7.16 -> 2.8.9 and v2.8.9 -> 2.9.3
- [x] Clean up old branches 2.7, 2.8
- [x] Update branch references on Rancher before release.
- [x] Update branch references on Rancher after release. 
- [x] Update product confluence table with necessary chart versions. 
--- 

#### Task Info 

`Coordination charts release between teams`:
- Negotiate with @Jono-SUSE-Rancher the due date for the Charts release.
- Communicate with company at #team-rancher-release-coordination channel the proper dates and tables.

`Execute batch releases for all versions`:
- Merge the batch releases.
- Sync and clean-up dev branches after batch release for `2.7` and `2.8`.
- Forward-port released charts from previous branches.
- Release forward-ported charts from previous branches.
- Sync and clean-up one last time for `2.7` and `2.8`.
- Monitor git mirror
- Communicate result to the company. 

`Update branch references for all versions on Rancher before release`:
- Merge update from `dev-v2.*` to `release-v2.*` branch references.

`Update branch references for all versions on Rancher after release`:
- Merge update from `release-v2.*` back to `dev-v2.*` branch references
