### ISSUE TITLE
[charts] Release 2.10.0 / 2.9.4 / 2.8.10

### ISSUE THREAD

**Issue by nicholasSUSE** [rancher/ecm-distro-tools#495]
Track all Helm Charts Release process activities for: [charts repository](https://github.com/rancher/charts)

- Rancher v2.10.0- Community
- Rancher v2.9.4 - Prime 
- Rancher v2.8.10 - (Prime)

--- 

#### Task Checklist
- [x] Coordination charts release between teams. 
- [x] Execute batch releases
- [x] Forward Port released charts
- [x] Clean up old branches
- [x] Update branch references on Rancher before release.
- [x] Update branch references on Rancher after release. 
- [x] Update product confluence table with necessary chart versions. 
--- 

#### Task Info 

`Coordination charts release between teams`:
- Negotiate with @Jono-SUSE-Rancher the due date for the Charts release.
- Communicate with company at #team-rancher-release-coordination channel the proper dates and tables.

`Execute batch releases for all versions`:
- Merge the batch releases.
- Sync and clean up dev branches after batch release for `2.8`
- Forward-port released charts from previous branches.
- Release forward-ported charts from previous branches.
- Sync and clean-up one last time for  `2.8`.
- Monitor git mirror
- Communicate results to the company. 

`Update branch references for all versions on Rancher before release`:
- Merge update from `dev-v2.*` to `release-v2.*` branch references.

`Update branch references for all versions on Rancher after release`:
- Merge update from `release-v2.*` back to `dev-v2.*` branch references
